# Proste workflow do wdrażania statycznego kontentu na GitHub Pages
name: Wdrażanie statycznego kontentu na Pages

on:
  # Uruchamiane po przesłaniu zmian na domyślny branch
  push:
    branches: ['main']

  # Pozwala na ręczne uruchomienie tego workflow z zakładki Actions
  workflow_dispatch:

# Ustawia uprawnienia GITHUB_TOKEN umożliwiające wdrażanie na GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Pozwala na jednoczesne wdrażanie
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Pojedyncze zadanie wdrażania, ponieważ tylko wdrażamy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Wczytaj repozytorium dist
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
